plugin: aws_ec2
regions:
  - eu-north-1
filters:
  instance-state-name: running
  tag:Name: redis_servers
hostnames:
  - private-ip-address
keyed_groups:
  - key: tags.Name
    prefix: "tag"
compose:
  ansible_user: "'ubuntu'"   # Most likely it's 'ubuntu' for Ubuntu instances
  ansible_ssh_private_key_file: "/home/ubuntu/anuj.pem"

